apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: 1-apps/apps
    repoURL: 'https://github.com/mmmayeras/argocd-samples'
    targetRevision: main
  project: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
